import discord
import os
from dotenv import load_dotenv
from discord.ext import commands as cmd

from MrHappy.fun import Fun
from MrHappy.economy import Economy
from MrHappy.zen import ZenQuotes
from MrHappy.moderation import Moderation

from MrHappy.diversão import Diversao
from MrHappy.economia import Economia

from MrHappy.keep_alive import keep_alive
load_dotenv()

TOKEN = os.getenv('TOKEN')
    

bot = cmd.Bot(
    command_prefix='=',
    description="A discord bot that has its own economic system, a rock paper scissors game and commands that sends zen quotes.",
)

bot.remove_command('help')


@bot.group(invoke_without_command=True)
async def help(ctx):
    embed = discord.Embed(title='Mr. Happy', description=f'{bot.description}', color=discord.Colour.orange())
    embed.add_field(name='Economy', value='`=help economy`')
    embed.add_field(name='Fun', value='`=help fun`')
    embed.add_field(name='Zen Quotes', value='`=help zen_quotes`')
    embed.add_field(name='Moderation', value='`Coming soon…`')
    embed.add_field(name='Help in portuguese', value='`=ajuda`')

    await ctx.send(embed=embed)


@help.command()
async def economy(ctx):
    embed = discord.Embed(title='Economy', description='All the economy commands', color=discord.Colour.orange())
    embed.add_field(name='work', value='work and get some money\n\n**Usage:**\n`=work`')
    embed.add_field(name='money', value='check your money or another user\'s money\n\n**Usage:**\n`=money [@user]`')
    embed.add_field(name='pay', value='give money to another user\n\n**Usage:**\n`=pay <@user> <amount>`')
    
    await ctx.send(embed=embed)

@help.command()
async def fun(ctx):
    embed = discord.Embed(title='Fun', description='All the fun commands', color=discord.Colour.orange())
    embed.add_field(name='ping', value='ping pong!\n\n**Usage:**\n`=ping`')
    embed.add_field(name='say', value='make me say a word or phrase\n\n**Usage:**\n`=say <word or "phrase">`\nphrases need to be in double quotes')
    embed.add_field(name='rps', value='rock paper scissors\n\n**Usage:**\n`=rps <rock, paper or scissors>`')
    
    await ctx.send(embed=embed)

@help.command()
async def zen_quotes(ctx):
    embed = discord.Embed(title='Zen quotes', description='All zen quotes commands, generated by https://zenquotes.io', color=discord.Colour.orange())
    embed.add_field(name='zenquote', value='A random zen quote\n\n**Usage:**\n`=zenquote`')
    embed.add_field(name='dailyquote', value='the zen quote of the day\n\n**Usage:**\n`=dailyquote`')
    
    await ctx.send(embed=embed)


@bot.group(invoke_without_command=True)
async def ajuda(ctx):
    embed = discord.Embed(title='Mr. Happy', description='Um bot para o discord que tem seu próprio sistema de economia, um jogo de pedra papel tesoura e citações zen (não traduzidas para o português ainda).', color=discord.Colour.orange())
    embed.add_field(name='Economia', value='`=ajuda economia`')
    embed.add_field(name='Diversão', value='`=ajuda diversao`')
    embed.add_field(name='Moderação', value='`Em breve…`')
    embed.add_field(name='Ajuda em inglês', value='`=help`')

    await ctx.send(embed=embed)

@ajuda.command()
async def economia(ctx):
    embed = discord.Embed(title='Economia', description='Todos os comandos de economia', color=discord.Colour.orange())
    embed.add_field(name='trabalhar', value='trabalhe e ganhe dinheiro\n\n**Uso:**\n`=trabalhar`')
    embed.add_field(name='dinheiro', value='olhe seu dinheiro ou o de outro usuário\n\n**Uso:**\n`=dinheiro [@usuário]`')
    embed.add_field(name='pagar', value='dê dinheiro a outro usuário\n\n**Uso:**\n`=pagar <@usuário> <quantidade>`')
    
    await ctx.send(embed=embed)

@ajuda.command()
async def diversao(ctx):
    embed = discord.Embed(title='Diversão', description='Todos os comandos de diversão', color=discord.Colour.orange())
    embed.add_field(name='fale', value='me faça falar alguma palavra ou frase\n\n**Uso:**\n`=fale <palavra ou "frase">`\nas frases tem que estar dentro de aspas duplas')
    embed.add_field(name='ppt', value='pedra papel tesoura\n\n**Uso:**\n`=ppt <pedra, papel ou tesoura>`')
    
    await ctx.send(embed=embed)
    
@bot.event
async def on_ready():
    print("I'm in")


keep_alive()


def run():
    bot.add_cog(Moderation(bot))
    bot.add_cog(Economia(bot))
    bot.add_cog(Diversao(bot))
    bot.add_cog(ZenQuotes(bot))
    bot.add_cog(Fun(bot))
    bot.add_cog(Economy(bot))
    bot.run(TOKEN)


if __name__ == "__main__":
    run()
